import type { Metadata } from 'next'
import { SpeedInsights } from '@vercel/speed-insights/next'
import './globals.css'

import { inter } from './fonts'

import { Provider } from '#/lib/providers'
import { Sidbar } from '#/components/sidebar'

export const metadata: Metadata = {
  title: 'Clover\'sBlog',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="light bg-red-200">
      <body className={inter.className}>
        <SpeedInsights />
        <Provider>
          <div className="container m-auto grid grid-rows-1 grid-cols-[340px_1fr]">
            <Sidbar />
            {children}
          </div>
        </Provider>
      </body>
    </html>
  )
}
