import type { Metadata } from 'next'
import './globals.css'

import { inter } from './fonts'

import { Provider } from '#/lib/providers'

export const metadata: Metadata = {
  title: 'Clover\'sBlog',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="light">
      <body className={inter.className}>
        <Provider>
          {children}
        </Provider>
      </body>
    </html>
  )
}
